{{- if and (.Values.multipleServices.enabled) ( eq .Values.ebpfOnly false ) ( .Values.apigeeServer.enabled ) }}
apiVersion: v1
kind: Service
metadata:
  name: agent-apigee
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "traceableai.labels" . | indent 4 }}
  annotations:
{{ include "traceableai.annotations" . | indent 4 }}
spec:
  type: {{ .Values.multipleServices.apigee.serviceType }}
  ports:
    - port: {{ .Values.apigeeServer.server.port }}
      name: tcp-apigee
      protocol: TCP
      targetPort: {{ .Values.apigeeServer.server.port }}
{{- if and (eq .Values.multipleServices.apigee.serviceType "NodePort") (gt (int .Values.multipleServices.apigee.nodePort) 0) }}
      nodePort: {{ .Values.multipleServices.apigee.nodePort }}
{{- end }}
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}