{{- if and (.Values.clusterRolesEnabled) (eq .Values.ebpfOnly false) }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Chart.Name }}-cluster-role-binding-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "traceableai.labels" . | indent 4 }}
  annotations:
{{ include "traceableai.annotations" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Chart.Name }}-cluster-role-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}