{{ if and (eq .Values.individualK8sServicesEnabled true) ( .Values.collectorEnabled ) (eq .Values.ebpfOnly false) }}
apiVersion: v1
kind: Service
metadata:
  name: collector
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "traceableai.labels" . | indent 4 }}
  annotations:
{{ include "traceableai.annotations" . | indent 4 }}
spec:
  type: {{ .Values.serviceType }}
{{ include "traceable-agent.collector.ports" . | indent 2 }}
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}