{{ if eq .Values.ebpfCaptureEnabled true }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.ebpfServiceAccountName }}
  namespace: {{ .Release.Namespace }}
  annotations:
{{ include "serviceAccountAnnotations" . | indent 4 }}
{{ include "traceableai.annotations" . | indent 4 }}
  labels:
{{ include "traceableai.labels" . | indent 4 }}
{{ end }}