{{ if and (eq (not .Values.k8sManifests) true) (eq .Values.ebpfOnly false) (eq .Values.extCapAuth.enabled false) }}
{{ if eq (include "useExternalTokenSecret" .) "false" }}
{{ if eq (include "refreshTokenFilePresent" .) "false" }}
{{ if eq (include "bootstrapRefreshTokenFromGcp" .) "false" }}
apiVersion: v1
kind: Secret
metadata:
  name: token-secret
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "traceableai.labels" . | indent 4 }}
  annotations:
{{ include "traceableai.annotations" . | indent 4 }}
type: Opaque
stringData:
  token: {{ include "traceableai.token" . }}
{{ end }}
{{ end }}
{{ end }}
{{ end }}