{{ if and (not .Values.k8sManifests) (ne .Values.imageCredentials.username "") (ne .Values.imageCredentials.password "") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "regcredSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "traceableai.labels" . | indent 4 }}
  annotations:
{{ include "traceableai.annotations" . | indent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "traceableai.imagePullSecret" . }}
{{ end }}