{{ if eq .Values.ebpfOnly false }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  annotations:
{{- include "serviceAccountAnnotations" . | indent 4 }}
{{ include "traceableai.annotations" . | indent 4 }}
  labels:
{{ include "traceableai.labels" . | indent 4 }}
{{ end }}