{{- if and (eq (include "tlsCertsMode" .) "external_tls_strings") (eq .Values.ebpfOnly false)}}
apiVersion: v1
kind: Secret
metadata:
  name: traceable-agent-cert
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "traceableai.labels" . | indent 4 }}
  annotations:
{{ include "traceableai.annotations" . | indent 4 }}
type: Opaque
data:
  root-ca.crt: {{ .Values.tlsPrivateCertificatesAsString.rootCAB64 | quote }}
  tls.crt: {{ .Values.tlsPrivateCertificatesAsString.certB64 | quote }}
  tls.key: {{ .Values.tlsPrivateCertificatesAsString.keyB64 | quote }}
{{- end }}